java:
  stage: test
  script:
    - mvn verify
  artifacts:
    when: always
    paths:
      - reports/manualLaunch/index.html
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml