package com.neolians.website.entity;

public class FactureInfo {
	public String puHt;
	public String quantite;
	public String pourcentage;
	public String totalRemisePourcentage;
	public String totalHt;
	public String totalTva;
	public String totalTtc;
	public String tva;
	public String raisonRemise;
	public String tauxRemise;
	public String Emetteur;
	public String objet;
	public String echeance;
	public String conditionParticulieres;
	public String montantFacturePrevisionnelle;
	public String commentaires;
	public Boolean afficherRemise;
	public Boolean afficherDetailProduit;
	public Boolean afficherPourcentage;
	public Boolean afficherDescriptionDetaillee;
	public String compte;
	public String contact;
	public String donneesComptable;
	public String delaiDePaiement;
	public String modeDePaiement;
	public String VRef;
	public String sousType;
	public String dateFacture;
	public String raisonSociale;
	public String langue;
	public String contactFacturation;

	public String dateDebut;
	public String dateFin;
	public String tvaMateriel;
	public String tvaOffrePersonalise;
	public String tvaOffreSupport;
	public String tvaSmartApp;
	public String ordreMateriel;
	public String ordreSmartApp;
	public String ordreOffreSupport;
	public String ordreOffrePersonalise;
	public String quantiteOffrePersonalise;
	public String quantiteOffreSupport;
	public String quantiteSmartApp;
	public String nomPremierJalon;
	public String nomDeuxiemeJalon;
	public String nomtroisiemeJalon;
	public String pourcentagePremierJalon;
	public String pourcentageDeuxiemeJalon;
	public String pourcentagetroisiemeJalon;
	public String dateFacturePremierJalon;
	public String dateFactureDeuxiemeJalon;
	public String dateFacturetroisiemeJalon;
}
